(define (problem hiking-problem-11-5-5)
  (:domain hiking)

  (:objects
    loc1 - loc
    loc2 - loc
    loc3 - loc
    loc4 - loc
    loc5 - loc
    loc6 - loc
    loc7 - loc
    loc8 - loc
    loc9 - loc
    loc10 - loc
    loc11 - loc
  )

  (:init
    (at loc1)
    (adjacent loc1 loc2)
    (adjacent loc2 loc1)
    (adjacent loc1 loc4)
    (adjacent loc4 loc1)
    (adjacent loc1 loc5)
    (adjacent loc5 loc1)
    (adjacent loc1 loc6)
    (adjacent loc6 loc1)
    (adjacent loc1 loc9)
    (adjacent loc9 loc1)
    (adjacent loc1 loc11)
    (adjacent loc11 loc1)
    (adjacent loc2 loc3)
    (adjacent loc3 loc2)
    (adjacent loc2 loc4)
    (adjacent loc4 loc2)
    (adjacent loc2 loc5)
    (adjacent loc5 loc2)
    (adjacent loc2 loc6)
    (adjacent loc6 loc2)
    (adjacent loc2 loc7)
    (adjacent loc7 loc2)
    (adjacent loc2 loc8)
    (adjacent loc8 loc2)
    (adjacent loc2 loc9)
    (adjacent loc9 loc2)
    (adjacent loc2 loc11)
    (adjacent loc11 loc2)
    (adjacent loc3 loc7)
    (adjacent loc7 loc3)
    (adjacent loc3 loc8)
    (adjacent loc8 loc3)
    (adjacent loc3 loc9)
    (adjacent loc9 loc3)
    (adjacent loc3 loc10)
    (adjacent loc10 loc3)
    (adjacent loc3 loc11)
    (adjacent loc11 loc3)
    (adjacent loc4 loc5)
    (adjacent loc5 loc4)
    (adjacent loc4 loc6)
    (adjacent loc6 loc4)
    (adjacent loc5 loc6)
    (adjacent loc6 loc5)
    (adjacent loc5 loc7)
    (adjacent loc7 loc5)
    (adjacent loc5 loc9)
    (adjacent loc9 loc5)
    (adjacent loc6 loc8)
    (adjacent loc8 loc6)
    (adjacent loc6 loc11)
    (adjacent loc11 loc6)
    (adjacent loc7 loc10)
    (adjacent loc10 loc7)
    (adjacent loc8 loc9)
    (adjacent loc9 loc8)
    (adjacent loc8 loc10)
    (adjacent loc10 loc8)
    (adjacent loc9 loc10)
    (adjacent loc10 loc9)
    (isHill loc10)
    (isHill loc2)
    (isHill loc5)
    (isHill loc8)
    (isHill loc4)
    (isWater loc7)
    (isWater loc3)
    (isWater loc6)
    (isWater loc9)
    (isGoal loc11)
  )

  (:goal (at loc11))

)