
"""
This file contains the global logger for the NL3PDDL project.
"""

import os
import logging

from pddl.parser.domain import DomainParser

from nl3pddl.config import LOG_LEVEL
from nl3pddl.params import feedback_pipeline_str
from nl3pddl.experiment_state import State

logging.basicConfig(level=logging.INFO)

logger = logging.getLogger(__name__)
logger.setLevel(LOG_LEVEL)

# CSV header for the results file
RESULTS_HEADER = [
    "trial",
    "domain_path",
    "provider",
    "model",
    "give_pred_descriptions",
    "desc_class",
    "feedback_pipeline",
    "landmark_runs",
    "val_runs",
    "hde_runs",
    "hde_timeout",
    "action_timeout",
    "action_timeout_cause",
    "evals_passed",
    "total_evals",
    #"domain_raw"
]

def gen_csv_results(s : State) -> tuple:
    """
    Generates a tuple of results for the experiment, to be written to the
    results file, Requires that the experiment has completed successfully.
    needs to match the RESULTS_HEADER.
    """
    return (
        #s["run_id"],
        s["PARAMS"].trial,
        s["PARAMS"].domain_path,
        s["PARAMS"].provider,
        s["PARAMS"].model,
        s["PARAMS"].give_pred_descriptions,
        s["PARAMS"].desc_class,
        feedback_pipeline_str(s["PARAMS"]),
        s["landmark_runs"],
        s["val_runs"],
        s["hde_iterations"],
        s["hde_timeout"],
        s["action_timeout"],
        s["action_timeout_cause"],
        s["evals_passed"],
        s["total_evals"],
        #s["json_last"].pddl_domain if s["json_last"] else ""
    )

def write_message_log(s : State, err_msg : str, results_dir : str) -> None:
    """
    Writes the message log to a file in the results directory.
    """
    domain_path = s['PARAMS'].domain_path.split("/")[-1]
    log_path = os.path.join(results_dir, f"""{s['PARAMS'].provider}_{s['PARAMS'].model}_{domain_path}_{s['PARAMS'].desc_class}_{s['PARAMS'].trial}_{feedback_pipeline_str(s['PARAMS'])}_messages.log""")
    with open(log_path, 'w', encoding="utf-8") as f:

        f.write("NON VAR INFO =========================================\n\n")
        #f.write(f"RUN ID: {s['run_id']}\n")
        f.write(f"TRIAL: {s['PARAMS'].trial}\n")
        f.write("\nExperiment Params ====================================\n\n")
        f.write(f"PROVIDER: {s['PARAMS'].provider}\n")
        f.write(f"MODEL: {s['PARAMS'].model}\n")
        f.write(f"DOMAIN PATH: {s['PARAMS'].domain_path}\n")
        f.write(f"DESC CLASS: {s['PARAMS'].desc_class}\n")
        f.write(f"FEEDBACK PIPELINE: {feedback_pipeline_str(s['PARAMS'])}\n")
        f.write(f"GIVE PRED DESCRIPTIONS: {s['PARAMS'].give_pred_descriptions}\n")

        if err_msg != "":
            f.write("\nERROR MESSAGE ======================================\n\n")
            f.write(err_msg + "\n")
            return
        
        f.write("\nEXPERIMENT RESULTS ===================================\n\n")
        f.write(f"DOMAIN CHECK RUNS: {s['domain_check_runs']}\n")
        f.write(f"LANDMARK RUNS: {s['landmark_runs']}\n")
        f.write(f"VAL RUNS: {s['val_runs']}\n")
        f.write(f"HDE ITERATIONS: {s['hde_iterations']}\n")
        f.write(f"HDE TIMEOUT: {s['hde_timeout']}\n")
        f.write(f"ACTION TIMEOUT: {s['action_timeout']}\n")
        f.write(f"ACTION TIMEOUT CAUSE: {s['action_timeout_cause']}\n")
        f.write(f"EVALS PASSED: {s['evals_passed']}\n")
        f.write(f"TOTAL EVALS: {s['total_evals']}\n")
        f.write("LANGGRAPH PATH:\n\t" + '->\n\t'.join(s['langgraph_path']) + "\n")
        
        f.write("\nFINAL DOMAIN =====================================\n\n")
        try:
            domain_str = DomainParser()(s["messages"].json_last()["pddl_domain"] if s["messages"].json_last() else "")
            f.write(str(domain_str))
        except Exception as e:
            f.write("No Domain was Generated by the Model, most likely because the pipeline never passed the domain construction stage.\n")

        f.write("\nMessages ===========================================\n\n\n")
        for msg in s["messages"].history():
            f.write(str(msg))
            # f.write(msg.type.upper() + "\n\n")
            # f.write(msg.content + "\n\n\n")