name: Test Suite

on:
  push:
    branches: [ main, daniel-huggingface ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install system dependencies for VAL
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    - name: Build VAL submodule
      run: |
        cd submodules/VAL
        mkdir -p build
        cd build
        cmake ..
        make
        cd ../../../

    - name: Test imports
      run: |
        python -c "import nl3pddl as n3p; print('✓ NL3PDDL imports successfully')"

